import { Threat } from '@/lib/stores/threat-store';

// Threat presets for dev dashboard - one per threat type
export const THREAT_PRESETS: Record<Threat['type'], Omit<Threat, 'id'>> = {
  asteroid: {
    type: 'asteroid',
    position: [20, 14, -35],
    size: 1.3,
    color: '#ff5733',
    label: 'DEV ASTEROID',
    detail: 'Test asteroid from dev dashboard',
    amount: 49.99,
    severity: 'danger',
    deflected: false,
    createdAt: Date.now(),
  },
  ion_storm: {
    type: 'ion_storm',
    position: [26, 16, -42],
    size: 1.5,
    color: '#a855f7',
    label: 'DEV ION STORM',
    detail: 'Test ion storm from dev dashboard',
    amount: 284,
    severity: 'warning',
    deflected: false,
    createdAt: Date.now(),
  },
  solar_flare: {
    type: 'solar_flare',
    position: [18, 15, -38],
    size: 2.0,
    color: '#fbbf24',
    label: 'DEV SOLAR FLARE',
    detail: 'Test solar flare from dev dashboard',
    amount: 31.98,
    severity: 'danger',
    deflected: false,
    createdAt: Date.now(),
  },
  black_hole: {
    type: 'black_hole',
    position: [30, 18, -48],
    size: 3.0,
    color: '#4c1d95',
    label: 'DEV BLACK HOLE',
    detail: 'Test black hole from dev dashboard',
    amount: 4500,
    severity: 'danger',
    deflected: false,
    createdAt: Date.now(),
  },
  wormhole: {
    type: 'wormhole',
    position: [19, 20, -50],
    size: 2.5,
    color: '#60a5fa',
    label: 'DEV WORMHOLE',
    detail: 'Test wormhole from dev dashboard',
    amount: 12,
    severity: 'info',
    deflected: false,
    createdAt: Date.now(),
  },
  enemy_cruiser: {
    type: 'enemy_cruiser',
    position: [25, 14, -36],
    size: 2.0,
    color: '#991b1b',
    label: 'DEV ENEMY CRUISER',
    detail: 'Test enemy cruiser from dev dashboard',
    amount: 847.99,
    severity: 'danger',
    deflected: false,
    createdAt: Date.now(),
  },
};

// Curated threats for demo presentation
export const DEMO_SCENE_THREATS: Threat[] = [
  {
    id: 'demo-asteroid-1',
    type: 'asteroid',
    position: [22, 15, -37],
    size: 1.5,
    color: '#ff5733',
    label: 'GYM $49.99/mo',
    detail: 'Zero usage for 47 days — renews in 5d',
    amount: 49.99,
    severity: 'danger',
    deflected: false,
    createdAt: Date.now() - 3600_000,
  },
  {
    id: 'demo-ion-storm',
    type: 'ion_storm',
    position: [28, 17, -44],
    size: 1.8,
    color: '#a855f7',
    label: 'DINING +142%',
    detail: 'Recreation Deck at 142% capacity',
    amount: 284,
    severity: 'warning',
    deflected: false,
    createdAt: Date.now() - 7200_000,
  },
  {
    id: 'demo-solar-flare',
    type: 'solar_flare',
    position: [19, 16, -40],
    size: 2.2,
    color: '#fbbf24',
    label: 'STREAMING $31.98',
    detail: 'Netflix + Hulu auto-renew in 48h',
    amount: 31.98,
    severity: 'danger',
    deflected: false,
    createdAt: Date.now() - 1800_000,
  },
  {
    id: 'demo-black-hole',
    type: 'black_hole',
    position: [32, 20, -50],
    size: 3.5,
    color: '#4c1d95',
    label: 'CREDIT DEBT $4,500',
    detail: 'Growing at 24.99% APR',
    amount: 4500,
    severity: 'danger',
    deflected: false,
    createdAt: Date.now() - 172800_000,
  },
  {
    id: 'demo-wormhole',
    type: 'wormhole',
    position: [24, 13, -46],
    size: 2.0,
    color: '#60a5fa',
    label: 'MISSED REWARDS $156/yr',
    detail: 'Wrong card for dining purchases',
    amount: 156,
    severity: 'info',
    deflected: false,
    createdAt: Date.now() - 43200_000,
  },
];
